import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import Contact from "./ContactUs/contact";
import Card from "@/components/Card";
import Card1 from "./card1/page";
import BlogPage from "./blog/page";
import FeedbackComponent from "./feedback/page";
import Characteristics from "./characteristics/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      {/* <Header /> */}
      {/* <Contact/>   */}
    {/* <BlogPage /> */}
    {/* <FeedbackComponent /> */}
    <Characteristics />
        {children}
        {/* <Footer /> */}
        </body>
    </html>
  );
}
